name: "Pull Request Comment Branch"

description: "Gets the head ref and sha of a pull request comment"

author: "xt0rted"

branding:
  icon: "message-square"
  color: "white"

inputs:
  repo_token:
    description: "GITHUB_TOKEN token or a repo scoped PAT"
    required: true
    default: ${{ github.token }}

outputs:
  base_ref:
    description: "The name of the branch the pull request will merge into."
  base_sha:
    description: "The head sha of the branch the pull request will merge into."
  head_ref:
    description: "The name of the pull request branch the comment belongs to."
  head_sha:
    description: "The head sha of the pull request branch the comment belongs to."
  head_owner:
    description: "The owner of the pull request branch the comment belongs to."
  head_repo:
    description: "The repository of the pull request branch the comment belongs to."

runs:
  using: "node16"
  main: "dist/index.js"
